
include build/top.make

BINARY = bardecode

BINARY_EXT = $(X_EXEEXT)
DEPS = $(lib_BINARY) $(X_OUTARCH)/utility/ArgumentList$(X_OBJEXT) $(X_MODULE)/bardecode$(X_LIBEXT)

CPPFLAGS += -I utility

include build/bottom.make

